apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
  namespace: stage
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8079
  selector:
    app: front-end
  type: LoadBalancer
